### ISSUE TITLE
Documentation for installation

### ISSUE THREAD

**Issue by jsundn** [creativecommons/garmonbozia#1]
I wonder where I can find documentation about dependencies and how to setup the application?

**Comment by mattl** [comment]
The development is a little sparse right now, but we'll be working on it more in the coming months. 

However, the dependency instructions at https://thelist.creativecommons.org/hacking/webapp/ will certainly help, as they're based on the same code base.

**Comment by rheaplex** [comment]
Brief installation instructions have been added.
