### ISSUE TITLE
Result Cache Root Directory and Template Directory Must Be Writable By Webserver

### ISSUE THREAD

**Issue by robmyers** [creativecommons/garmonbozia#11]
e.g.:

chmod a+x . themes/cc/templates_c

Can we move the cache dir out of the webserver root?

Or switch to redis for caching the results (we'd trade storage space for speed)?

**Comment by benson70565** [comment]
Check

**Comment by robmyers** [comment]
There's a redis implementation of the search cache. We can replace that with a MySQL one easily enough.

Making the cache directory writable is now in the README.
