### ISSUE TITLE
Requires php 5.6 (5.5)?

### ISSUE THREAD

**Issue by robmyers** [creativecommons/garmonbozia#14]
php 5.4 fails to compile try { x; } finally {}

5.6 is fine. Probably a 5.5 thing but specify 5.6 as we know that works.

Make a note in installation instructions.

**Comment by rheaplex** [comment]
Used composer to do this - https://github.com/creativecommons/garmonbozia/commit/dfe15c86e5732ad97b3bf07eb3e9086ec4632ba9
