### ISSUE TITLE
Where Should We Search?

### ISSUE THREAD

**Issue by robmyers** [creativecommons/garmonbozia#19]
Which services and sites would you like to search for Creative Commons licensed work?

**Comment by janeatcc** [comment]
Current stuff listed at http://search.creativecommons.org/ + these Platforms: 

* Flickr
* Vimeo
* Internet Archive
* Wikimedia Commons
* YouTube
* Medium
* Slideshare/LinkedIn
* Wordpress
* 500px
* Behance
* Bandcamp
* Soundcloud
* Thingiverse
* Sketchfab
* DeviantArt
* Free Music Archive
* GitHub
* Noun Project
* Pinshape
* Scribd
* MIT OCW - and other OCW sites
* Other OER sites from http://open4us.org/find-oer/

And more as we come across and engage with additional platforms. Is that a good list to start?

**Comment by janeatcc** [comment]
If any are not machine-readable, let me know -- and that can be one of our requirements of them to include in search, eg. working with Sketchfab to get it machine-readable in addition to other features.

**Comment by robmyers** [comment]
For MVP there are two options:

1. Closely follow what the current search provides.
2. One commercial & one community image source, plus OER.

We need to prioritise.
