### ISSUE TITLE
Please support Ipernity

### ISSUE THREAD

**Issue by forteller** [creativecommons/garmonbozia#2]
Ipernity, www.ipernity.com, is a Flickr like community, which is quite huge, but mostly used by people in France. Still the UI is in English, they have a ton of CC licensed images, and they have a search engine which lets you filter the results on CC licenses, and an API http://www.ipernity.com/help/api/

So I would like you to please add support for Ipernity to the new CC Search. Thanks!

**Comment by forteller** [comment]
What happened?

**Comment by rheaplex** [comment]
This project has been superceded by the new search project (open-ledger) so I am closing tickets here.

Do add a note about ipernity to open-ledger!
