### ISSUE TITLE
Media Categories - Which Should We Have?

### ISSUE THREAD

**Issue by robmyers** [creativecommons/garmonbozia#23]
Currently we have:
* Images
* Video
* Audio
* Books

Each site may provide more than one medium, e.g. flickr provides images and video, archive.org provides all of the above.

Other possible media for discussion:
* Presentations
* Blog Posts
* Open Educational Resources
* Academic Papers
* Web Sites
* Clip Art
* 3D printable models
* Animation models
* Game media
* Social media posts
* Music
* Radio shows
* Audio samples
* Wikis

Ideally we will have categories that are general enough that people will only need to run one search to get what they want, and specific enough that they won't get the wrong kind of media - e.g. complex open meshes for 3D printing.

What other categories of media can people think of?

Are any of these categories too broad / narrow / redundant / bad ?

Is it worth dividing up mass / educational / alternative / social media?

And what about "safe search"?

**Comment by DavidHaskiya** [comment]
Just a comment from 2 cents of experience at Europeana: You'll have a big challenge in doing the more fine grained resource typing as in your second bullet lists. Reason being that (unless you want to limit your search to English sources only) you'll have to have a very multi-lingual thesaurus of resource types to back your service. And that only works if the sources use the same resource typing list as you do or you have mappings from their resource types to your resource types. Your best chance to build such a thesaurus would be to base it on Wikidata terms (or Dbpedia, but I think Wikidata has the momentum and is also CC0) which has labels in loads of languages for each term.

This is the main reason that we at Europeana (with metadata records in 31 languages or so) are "stuck" at the simple media types Text, Image, Video, Sound recording and 3D. We chose Text over Books as it's more generic and covers also magazines, articles, letters, or any other resource type dominated by text. We still haven't surmounted that challenge.

**Comment by mattl** [comment]
Thanks for the insight, David.

**Comment by robmyers** [comment]
We're using simple categories. Plus or minus OER.
