### ISSUE TITLE
Add Europeana as a source

### ISSUE THREAD

**Issue by DavidHaskiya** [creativecommons/garmonbozia#29]
I know it's a bit self-promotional but if you add Europeana as a source you also add the hundreds of Europeana GLAM-partners who have marked up their collections with CC-licences and or the Public Domain marks. Most of those partners don't have APIs of their own but indirectly via us they do.

You can use the RIGHTS facet and query our API like e.g. so:
http://www.europeana.eu/api/v2/search.json?query=stained%20glass&qf=RIGHTS:http://creativecommons.org/licenses/by-nc-sa/*&wskey=xxx to represent a user searching for stained glass licensed CC-BY-NC-SA. 

In this example I put a wildcard at the end of the license URL because I'm not sure the version is very relevant. You could search for an exact version as well. You can user boolean queries to query on multiple license values. API-docs here http://labs.europeana.eu/api/introduction/ 

Get in touch if you have any questions!

**Comment by mattl** [comment]
Thanks David. This will be good to see how easy we can add new sources. Is there an easy way to return only images, only textbooks, etc?

**Comment by mzeinstra** [comment]
Hi David and Matt,

The Europeana data model can be somewhat difficult to understand. I believe you want to present the images themselves on your new search platform right? Then you would want to use the link in edm:Preview to get a preview of the media.

I wrote a few scripts interacting with the Europeana dataset as part of our collaborations. One of them can be found here: https://github.com/mzeinstra/Europeana-to-Amazon-s3/blob/master/API-CRF-images.php maybe that can serve as some inspiration for you.

It's up to you if you want to link to Europeana or use edm:isShownAt to have a direct link to the media page on the page of one of the hundreds of partners or use a link to the media on the Europeana.eu site.

**Comment by DavidHaskiya** [comment]
There's a media type facet that's straight forward to use if you want only images, only sound, only video, etc. Just add qf=TYPE:IMAGE to your search call (TYPE:VIDEO, TYPE:TEXT, TYPE:SOUND, TYPE:3D for the other media types).

Depending on how you want the UI of your search engine results pages to look there are also different response profiles available ranging from minimal metadata (suitable for grid style results pages) to rich metadata (suitable for list style results pages or for basic display of individual items), see http://labs.europeana.eu/api/search/#metadata-sets 

@mzeinstra Difficult to understand! Surely you jest? ;-)
