### ISSUE TITLE
Allow to search content across multiple licenses

### ISSUE THREAD

**Issue by marinintim** [creativecommons/garmonbozia#30]
e.g., CC-SA, CC, and public domain in one search.

**Comment by mattl** [comment]
Yeah, we have a plan to support this as essentially something like "Show me works I can build upon commercially" which would then return PDM, CC0, CC BY, CC BY-SA works.

**Comment by mattl** [comment]
Very much like how Flickr does/did it.

**Comment by robmyers** [comment]
Yes we can do something like that, we should make sure the search source architecture handles that in a robust way so e.g. if RandomAPI only lets you search for one license at a time we fire off a search for each in parallel.

Not sure if/how that affects caching.

**Comment by robmyers** [comment]
Rolled in to #34 .
