### ISSUE TITLE
Should the test site be linked to from CC Search?

### ISSUE THREAD

**Issue by mattccanz** [creativecommons/garmonbozia#31]
Search: Hi all - can I suggest that the test site not be linked to quite so prominently on CC Search, especially when it still seems to be very early stages in development?

CC Search is a tool used by a bunch of people, including teachers who push students there. It's a tool used by people who are relatively intimidated by licensing & copyright & are trying to do the 'right thing' and don't want to fiddle with advanced search filters. It's best to keep things as simple as possible for them.

The new tool, when it's done, will be awesome - but IMO this is not the community of people to push to testing the site, especially at this early stage.  

Sorry for the slightly negative feedback -- I'm just actively pushing older teachers and younger students that way, and am keen not to confuse them, especially when the new search isn't quite working. 

Cheers,
Matt
CC New Zealand

**Comment by mzeinstra** [comment]
I agree

I too use search.creativecommons.org in all my presentation for teachers and creative professionals. These people can get easily distracted.

**Comment by robmyers** [comment]
Moved new search link to bottom of page ( https://github.com/creativecommons/search/commit/39c68c32b6fc41c81e4dec0b048c8d8699b81ccf ).
