### ISSUE TITLE
Needs design specifications to avoid unnecessary feedback

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#32]
Hi,

Given that newsearch.creativecommons.org is live and you are pointing to it, I want to see what the final product will look like. This avoids unnecessary feedback from my end.

- [ ] I do not like the way you can only select one license
- [ ] That you need to understand CC licensing before you can use the tool
- [ ] That results are not separated in their source platform 
- [ ] That you do not do proper attribution (you are CC, you need to give the right example) Consider a hover information button or other type of overlay. Now you are breaking the license agreements..
- [ ] That there is no information about source platforms.

Consider posting the final design sketches on GitHub to avoid these probably unnecessary tickets.

**Comment by mattl** [comment]
One bug per issue please :)

**Comment by mzeinstra** [comment]
There is one bug here :)

Where are the design specifications? Or do you want me to flood you with all remarks I have about your online version so you can close them because they are already on some roadmap?

**Comment by mattl** [comment]
This is five issues. Please make issues for these so we can resolve them.

**Comment by mzeinstra** [comment]
There you go, you can re-open this ticket.
