### ISSUE TITLE
I need to be able to select more than one license

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#34]
I do not like the way you can only select one license

**Comment by robmyers** [comment]
The user should definitely be able to select more than one license. This ties in with #35 .

The single select is an artefact of this pre-pre-pre-alpha version and will be changed in a future version.

**Comment by robmyers** [comment]
This also ties in with #30.

**Comment by robmyers** [comment]
We need to be able to handle:

 * Multi-License select (e.g BY-SA and BY-NC-ND).
 * Module select (e.g. BY, SA, ND)
 * Use case select (e.g. work that can be modified, but not commercially)

This *may* be limited by the search APIs we use, but wherever possible we should provide this functionality. In theory we can just make multiple single-license searches for APIs that don't support anything else, although this will be costlier in terms of bandwidth etc.
