### ISSUE TITLE
Change input style for licensee

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#35]
ATM  you need to understand CC licensing before you can use the tool, you should be able to select what you need to do for what purpose instead of selecting a license

**Comment by robmyers** [comment]
Yes Matt also mentioned that we should have the "use commercially, be able to remix"-style of license selection *as well* as choosing by license name.

I agree that we should have both, although we don't want to clutter the UI or make it too complex so we'll need to do this carefully.

If possible I'd like to use the by-purpose/affordance choices to educate people about the licenses as well. e.g. selecting "remix" visibly selects CC0/cc-by/cc-by-sa .
