### ISSUE TITLE
Use proper attribution

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#37]
Use proper attribution (you are CC, you need to give the right example) Consider a hover information button or other type of overlay. 

Now you are breaking the license agreements..

**Comment by robmyers** [comment]
This is pre-pre-release software, so the individual results pages are unfinished. In addition to lacking attribution the title is a placeholder and the clickable link to the original link is broken.

We need to provide an example of best practice for attribution, making it easy for people to copy attribution information. Given the increasing prevalence of mobile platforms we probably need to avoid ephemeral UI for this. A text field below the work with a big "copy correct attribution" button is probably the most obvious/easily usable UI.

**Comment by mzeinstra** [comment]
I agree,

However although there is not a release of the new search site, you are linking to it and it is publicly available. The licenses do not distinguish between what the developers consider a release and what not. As it stand you are breaking the license and minimal proper attribution should your top priority. 

We have this saying in Dutch that you have to be 'more Catholic than the Pope'. Because CC produces and promotes the licenses you should not be publicly caught not following its requirements.

**Comment by robmyers** [comment]
We've moved the link down the page on the current search page, and added a "work in progress" disclaimer to the new search page.

I do want to improve that page next ("Placeholder Title" drives me crazy) so we will definitely fix this shortly.

**Comment by ryanmerkley** [comment]
Let's remove the link until we meet the attribution requirement.

**Comment by robmyers** [comment]
Link removed for now. https://github.com/creativecommons/search/commit/0ff8d2e3c04943faab95886e9cc71e83ba4a7226

Requirement incorporated into #43, closing.

**Comment by KKcompany39** [comment]
5 months ago
