### ISSUE TITLE
Create API for affiliate sites

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#42]
The current search.creativecommons.org is being used on some affiliate sites using its API functionality. Actually this API was a side effect of making the search available for people who do not use javascript. 

I don't believe that PHP scripts tracks use at the moment, however I know of some affiliate sites using it like.
http://www.creativecommons.org.uk/ 
http://creativecommons.nl/ 

I believe it really adds value to our local initiatives.

**Comment by robmyers** [comment]
After discussing this with Maarten at the Global Summit, I refactored Gamonbozia so that it is implemented as a web API that the web UI then consumes.

There is not documentation for this yet (and it hasn't been tested outside of this context), but it is now part of the codebase.
