### ISSUE TITLE
help

### ISSUE THREAD

**Issue by motorhead73** [creativecommons/garmonbozia#5]
please help me

**Comment by mattl** [comment]
How can we help? :)

**Comment by WildBearAttack** [comment]
I am really confused about what happened to the search.creativecommons.org site. I loved using it. I had to look in the wayback machine to find the link they had posted about it being replaced soon and it has led me here. But I have no idea what this is. Is there a new search engine I can use? Why was the old one taken down? I thought it worked great.

**Comment by mattl** [comment]
We're currently having some technical issues with it. It'll be back later
today.

---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by robmyers** [comment]
SIte is now back.
